---
abstract: 'Perl extension for International Standard Serial Numbers'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  Test::More: '0.94'
configure_requires:
  Exporter: '0'
  ExtUtils::MakeMaker: '6.64'
  File::Spec::Functions: '0'
  strict: '0'
  subs: '0'
  vars: '0'
  warnings: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-ISSN
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.008'
resources:
  bugtracker: https://github.com/briandfoy/business-issn/issues
  homepage: https://github.com/briandfoy/business-issn
  repository: https://github.com/briandfoy/business-issn.git
version: '1.003'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
